### ISSUE TITLE
保存先の指定

### ISSUE THREAD

**Issue by mamezou10** [yyoshiaki/ikra#21]
都度いろいろDLしなくてすむと便利だなと思っています
もろもろが入った場所で実行して、吐き出される子たちを別のところに保存できるようなオプションつけてもらえると嬉しいです
ご検討よろしくお願いします！

**Comment by yyoshiaki** [comment]
https://github.com/yyoshiaki/auto_counttable_maker/issues/10

が実装されたら考えましょう！

**Comment by yyoshiaki** [comment]
密かに足してみました。
-o optionです。試してみてください！
