### ISSUE TITLE
PE file name (fastq branch)

### ISSUE THREAD

**Issue by yyoshiaki** [yyoshiaki/ikra#29]
現状
`*_1.fastq.gz`, `*_2.fastq.gz`
の代わりに
`*.fastq.gz`
を引数に入れるとうごく。

あとで修正。

-----

fq.gz はfastq.gzにmvすればいい？

**Comment by mamezou10** [comment]
*_R1.*, *_R2.*で出るタイプのPEはどうするのが良いですかね
とりあえずディレクトリ名を変えたらそこは通るようになるようですが。。

そもそもR1/R2って一般的な形式なのかがちょっと分からないです

**Comment by yyoshiaki** [comment]
いっぱいありそうですね！！どうしましょう笑

https://cell-innovation.nig.ac.jp/surfers/FASTQ.html

**Comment by mamezou10** [comment]
おおこんな資料が！ありがとうございます
本当ですねぇ。。
こんだけ違うと対応の方針も悩ましいですが
いずれにしても、成形してもらうか表記ゆらぎに対応できるようにするのの二択ですね？
タスクがたくさんあって楽しいですね（汗）

**Comment by bonohu** [comment]
まだこんなものが。かなり古い情報です。

> https://cell-innovation.nig.ac.jp/surfers/FASTQ.html

ただ、ペアエンドの書き方は色々ですね。
fastq-dumpのそれとfasterq-dumpのそれも（デフォルトだと）違ってますし。

**Comment by yyoshiaki** [comment]
デフォルトは今のままで、オプションで指定できるようにするのがいいですかね。

**Comment by yyoshiaki** [comment]
対応しました！お試しあれ！
