### ISSUE TITLE
single end？

### ISSUE THREAD

**Issue by aibo3** [yyoshiaki/ikra#56]
single endのSRRをいれたら途中で止まってしまいました。
fastqがダウンロードされたあとpairedのような認識になってしまった？
ご指導あればお願いします。

CSVの中身は
name | SRR | Layout
D1_nTconv | SRR5058658 | SE

コード　
ikra % cd csvのフォルダ && bash ../../ikra.sh ファイル名.csv human

エラー
+ SRR=SRR5058658
+ '[' $'SE\r' = SE ']'
+ [[ ! -f ./SRR5058658_1_val_1.fq.gz ]]
+ docker run -u 501:20 --rm -v /　フォルダ名　　i:/home -e HOME=/home --workdir /home quay.io/biocontainers/trim-galore:0.6.3--0 trim_galore --paired ./SRR5058658_1.fastq.gz ./SRR5058658_2.fastq.gz
.......
gzip: ./SRR5058658_1.fastq.gz: No such file or directory
Input file './SRR5058658_1.fastq.gz' seems to be completely empty. Consider respecifying!

**Comment by yyoshiaki** [comment]
excelでcsvを作成したときに行末に\rが入ってしまうことが原因です。
もう一列ダミーの列を作っていただけますでしょうか？

**Comment by aibo3** [comment]
ありがとうございます。

下記testのように
name | SRR | LayoutFoxp3 | CNS2
Foxp3high_CNS2KO_1 | SRR1269713 | SE | Foxp3high
D1_nTconv | SRR5058658 | SE　の右側列に何らかの数字文字列をつくるということですね

試してみます。
