### ISSUE TITLE
salmonの部分でうまく動きません。

### ISSUE THREAD

**Issue by yonezawa-sora** [yyoshiaki/ikra#75]
`cd test/Illumina_PE && bash ../../ikra.sh SRP150441_PE_SRR.csv human -t 16 -o SRP150441_output.tsv`

M1のMacで試してみたところ、以下のようなエラーがでました。

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/103710902/177270294-84fa446f-41eb-473a-b5dd-af9614ef3383.png">

もういちどikraを再度ダウンロードしなおしてやりなおそうと考えています。スレッド数の指定などにも問題があったかと思うのでもう一度確認します。

もし解決法がありましたら教えていただけますと幸いです。よろしくお願い致します。

**Comment by yyoshiaki** [comment]
salmon indexが適切にできていないように思いますが、salmon indexのログとかはどうなってますでしょうか。

**Comment by yonezawa-sora** [comment]
こちらがsalmonのindexです。よろしくお願いします。
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/103710902/177435670-9af0b277-7e01-4dd9-90b5-2c0b480b6eb5.png">

**Comment by yonezawa-sora** [comment]
salmonのlogは以下のようになっていました
![image](https://user-images.githubusercontent.com/103710902/177661531-afdfd532-e1e6-462b-8337-c232bc981e05.png)

Dockerのメモリは32GBに設定して行っていました

よろしくお願いします。

**Comment by yyoshiaki** [comment]
手元のM1 MBAでは正常にindexが作成され、出力も正常でした。
すみませんが、再現とれません。何度かやり直す、salmonのdockerのversionを1.4 -> 1.9などに変更する、など選択肢は考えられますが、いかがでしょう。

**Comment by yonezawa-sora** [comment]
ありがとうございます。
ikraの再インストール、salmonのversionの変更など試してみます。

**Comment by yonezawa-sora** [comment]
M1でikraの再取得を行った後、salmonのversionを1.9に変更して何回か試してみたところ、tsvファイルの出力までうまく動くようになりました。ご対応いただきありがとうございました。
