### ISSUE TITLE
multiqc : searching : /home で止まる

### ISSUE THREAD

**Issue by Takamoto36** [yyoshiaki/ikra#78]
これまで問題なく解析できoutput.tsv が出力できていたのですが，下記添付のスクショの通り”multiqc : searching : /home”で止まり，この先の解析が進まなくなりました．原因や対処方法わかられましたらご教示ください．　
![ikra](https://github.com/yyoshiaki/ikra/assets/137237242/3f6fc047-8048-40aa-9ab6-e2d201058c13)

**Comment by yyoshiaki** [comment]
コンピュータのホームディレクトリ全体が探索対象になっているためだとおもわれます。
コマンドの指定の際のパスが良くないことが予想されます。
どのようになコマンドで実行していますか？

**Comment by Takamoto36** [comment]
ご回答ありがとうございます．
ikra.shファイルがあるディレクトリ（ikra-master）にcsvファイル（name,SRR,Layout）を置き，
cd /mnt/e/User/desktop/ikra-master　のコマンドで実行しております．

**Comment by Takamoto36** [comment]
すみません解決いたしました。
ディレクトリ（ikra-master）が解析データでいっぱいになっており100GBを超えていたので、
データを移動させたところ問題は解決しました。ディレクトリの容量が関係していたのかもしれません。
失礼いたしました。
