### ISSUE TITLE
ftp server connection failed

### ISSUE THREAD

**Issue by kayotan** [yyoshiaki/ikra#79]
以下のログが出力されたのですが、どのように解決すればよろしいでしょうか？よろしくお願いいたします。

ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/gencode.v37.metadata.HGNC.gz
=> ‘gencode.v37.metadata.HGNC.gz’
Connecting to ftp.ebi.ac.uk (ftp.ebi.ac.uk)|193.62.193.165|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/databases/gencode/Gencode_human/release_37 ... done.
==> SIZE gencode.v37.metadata.HGNC.gz ... 1499316
==> PASV ... couldn't connect to 10.34.22.86 port 47191: Connection timed out

**Comment by yyoshiaki** [comment]
ftpの箇所をhttpsに置き換えると動く場合があるようです。
