### ISSUE TITLE
-ctのオプションについて

### ISSUE THREAD

**Issue by Ayum-dev** [yyoshiaki/ikra#81]
一番最初にRNA-seqの解析で使えるようになったのがikraで、最初に結果を得られたときは感動いたしました。
NGS解析の最初の一歩を踏み出せたことに本当に感謝しております。

ところで、最近genecodeでnoncode RNAが増えたので、-ctを使ってみようと思ったら、gencode.vM36.pc_transcripts.fa.gzがダウンロードされてしまいました。
これだと-pcのオプションを選んだ時と同じものになってしまいます。

ですから-ctの場合はscriptの104-105行目
        '-ct'|'--comprehensive-transcripts' )
            IF_PC=true; shift
ここの部分を
        '-ct'|'--comprehensive-transcripts' )
            IF_PC=false; shift
と書き換えたらgencode.vM36.transcripts.fa.gzがダウンロードされるようになりました。
-ctの場合gencode.vM36.transcripts.fa.gzがダウンロードされるのであってますでしょうか？
ご検討よろしくお願いたします。

**Comment by yyoshiaki** [comment]
ありがとうございました、対処しました。

https://github.com/yyoshiaki/ikra/commit/c242855e88bfc4fc781c82ee4c6c20249cd18bf1
